version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: docker.host:5000/library/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DayPay
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  redis:
    image: docker.host:5000/library/redis:latest
    ports:
      - "6379:6379"
  nginx:
    image: docker.host:5000/library/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./media:/app/media
    depends_on:
      - web