version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn DayPay.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/DayPay/staticfiles
      - media_volume:/DayPay/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/DayPay/staticfiles
      - media_volume:/DayPay/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: