version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:./
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=daypayuser
      - POSTGRES_PASSWORD=D@ypay1234
      - POSTGRES_DB=daypay
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data: